name: Anavaradha Codes Web App CI/CD

on:
  push:
    branches:
      - main # Triggers the workflow on push to the main branch

jobs:
  build_and_deploy_job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14" # Use the Node.js version that your React app requires

      - name: Install Dependencies
        run: |
          npm install
          npm run build
