name: Deploy App

# This triggers the deploy workflow when the build workflow completes.
on:
  workflow_run:
    workflows: ["Build App"] # Name of the build workflow
    types:
      - completed # Run this workflow after the build workflow finishes (whether success or failure).

jobs:
  deploy:
    runs-on: ubuntu-latest

    # This ensures that the deploy job only runs if the build workflow was successful.
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm install

      - name: Run linting
        run: npm run lint

      - name: Build app
        run: npm run build

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.9.6

      - name: Terraform Init
        working-directory: infra
        env:
          ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
          ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
        run: terraform init

      - name: Terraform Apply
        working-directory: infra
        env:
          ARM_CLIENT_ID: ${{ secrets.AZURE_CREDENTIALS.clientId }}
          ARM_CLIENT_SECRET: ${{ secrets.AZURE_CREDENTIALS.clientSecret }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_CREDENTIALS.subscriptionId }}
          ARM_TENANT_ID: ${{ secrets.AZURE_CREDENTIALS.tenantId }}
        run: terraform apply -auto-approve -var "resource_group_name=anavaradhacodes" -var "storage_account_name=anavaradhacodes"

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Upload to Azure Blob Storage
        run: |
          az storage blob upload-batch -d \$web --account-name anavaradhacodes -s dist/
