name: Deploy App

# This triggers the deploy workflow when the build workflow completes.
on:
  workflow_run:
    workflows: ["Build App"] # Name of the build workflow
    types:
      - completed # Run this workflow after the build workflow finishes (whether success or failure).

jobs:
  deploy:
    runs-on: ubuntu-latest

    # This ensures that the deploy job only runs if the build workflow was successful.
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "20"

      - name: Install Dependencies
        run: npm ci

      - name: Build React App
        run: npm run build

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Terraform Init
        run: terraform init

      - name: Terraform Apply
        run: terraform apply -auto-approve

      - name: Upload React Build to Blob Storage
        run: |
          az storage blob upload-batch \
            --destination '$web' \
            --account-name $AZURE_STORAGE_ACCOUNT \
            --source ./dist \
            --auth-mode key
        env:
          AZURE_STORAGE_ACCOUNT: anavaradhacodessg
          AZURE_STORAGE_KEY: ${{ secrets.AZURE_STORAGE_KEY }}
